# Modify all lines indicated with MODIFY
outname: "ALL" # name you want to give to any output
models: #!! ONLY USE TEXT AND NUMBERS FOR NAMING MODELS.  List PGS models to use
  "model1":
      model_file: "/path/to/pgs/model" # MODIFY
      model_build: "hg38" # MODIFY confirm what genome build the model data is in
  "model2":
      model_file: "/path/to/pgs/model" # MODIFY confirm what genome build the model data is in
      model_build: "hg38" # MODIFY 
genotypes: #!! ONLY USE TEXT AND NUMBERS FOR NAMING DATASETS.  List one or more plink prefixes for data to be 
  "dataset1":
      data: "/path/to/plink/prefix" # MODIFY
      geno_build: "hg38" # MODIFY confirm what genome build the genotype data is in
  "dataset2":
      data: "/path/to/plink/prfix" # MODIFY
      geno_build: "hg38" # MODIFY confirm what genome build the genotype data is in
singularity:
  image: "/path/to/singularity/image" # TO CREATE
CrossMap:
  exec: "/home/araduski/araduski/.local/bin/CrossMap.py" 
  download_chains: 'false' # if set to TRUE, provide paths to download
  chain_to_hg19: "/home/araduski/araduski/misc/hg38ToHg19.over.chain.gz"
  chain_to_hg38: "/home/araduski/araduski/misc/hg19ToHg38.over.chain.gz"
  threads: "12"
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load R/4.1.0"
python: 'python'
run_settings:
  local_run: "false"
  cluster_config: "workflow/cluster_slurm.yaml"
  scheduler: "slurm"