# Modify all lines indicated with MODIFY
outname: "OUTPUT_NAME" # name you want to give to any output
model_name: "model_name"#!! ONLY USE TEXT AND NUMBERS FOR NAMING MODELS.  List PGS models to use
model_file: "/path/to/pgs/model" # MODIFY
model_build: "hg38" # MODIFY confirm what genome build the model data is in
genotype_name: "genotype_dataset_name" #!! ONLY USE TEXT AND NUMBERS FOR NAMING DATASETS.  List one or more plink prefixes for data to be 
genotype_data: "/path/to/plink/prefix" # MODIFY
genotype_build: "hg38" # MODIFY confirm what genome build the genotype data is in
singularity:
  image: "/path/to/singularity/image" # TO CREATE
perform_crossmap: 'true' # MODIFY - should the model coordinates be lifted over to match genotype coordinates i.e. are the two files in different coords?
CrossMap:
  exec: "/home/araduski/araduski/.local/bin/CrossMap.py" 
  download_chains: 'false' # if set to TRUE, provide paths to download
  chain_to_hg19: "/home/araduski/araduski/misc/hg38ToHg19.over.chain.gz"
  chain_to_hg38: "/home/araduski/araduski/misc/hg19ToHg38.over.chain.gz"
  threads: "12"
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load R/4.1.0"
python: 'python'
run_settings:
  local_run: "false"
  cluster_config: "workflow/cluster_slurm.yaml"
  scheduler: "slurm"
